export const AUTH_RECEIVED = 'auth/RECEIVED'
export const CLAN_RECEIVED = 'clan/RECEIVED'
export const CLAN_MEMBERS_RECEIVED = 'clan/members/RECEIVED'
export const USER_RECEIVED= 'user/RECEIVED'
export const CLAN_LIST_MEMBERS_LOADED = 'clan/list/members/RECEIVED'
export const CLAN_LIST_LOADED = 'clan/list/RECEIVED'